// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VxPayBridge.API.Database;

#nullable disable

namespace VxPayBridge.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260611184713_AddUserAuthentication")]
    partial class AddUserAuthentication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VxPayBridge.API.Database.Entities.AppUser", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelephoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TelephoneNumber")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("VxPayBridge.API.Database.Entities.ClientApp", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientSecretHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebhookSigningSecret")
                        .HasColumnType("text");

                    b.Property<string>("WebhookUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ClientApps");
                });

            modelBuilder.Entity("VxPayBridge.API.Database.Entities.LedgerAccount", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AudType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ClientAppID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PendingBalance")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("ClientAppID", "AudType", "AudID", "Currency")
                        .IsUnique();

                    b.ToTable("LedgerAccounts");
                });

            modelBuilder.Entity("VxPayBridge.API.Database.Entities.LedgerEntry", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ClientAppID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LedgerAccountID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PaymentTransactionID")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WithdrawalID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("LedgerAccountID");

                    b.HasIndex("PaymentTransactionID");

                    b.HasIndex("WithdrawalID");

                    b.HasIndex("ClientAppID", "Reference")
                        .IsUnique();

                    b.ToTable("LedgerEntries");
                });

            modelBuilder.Entity("VxPayBridge.API.Database.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessCode")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("AudID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AudType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorizationUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("ClientAppID")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GatewayTransactionID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("ClientAppID", "ClientReference")
                        .IsUnique();

                    b.HasIndex("ClientAppID", "AudType", "AudID");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("VxPayBridge.API.Database.Entities.UserOtp", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("UserID", "ExpiresAt");

                    b.ToTable("UserOtps");
                });

            modelBuilder.Entity("VxPayBridge.API.Database.Entities.WebhookEvent", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientAppID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GatewayTransactionID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("ClientAppID");

                    b.ToTable("WebhookEvents");
                });

            modelBuilder.Entity("VxPayBridge.API.Database.Entities.Withdrawal", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("AudID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AudType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ClientAppID")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("LedgerAccountID")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecipientCode")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransferCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("LedgerAccountID");

                    b.HasIndex("TransferCode");

                    b.HasIndex("ClientAppID", "ClientReference")
                        .IsUnique();

                    b.HasIndex("ClientAppID", "AudType", "AudID");

                    b.ToTable("Withdrawals");
                });

            modelBuilder.Entity("VxPayBridge.API.Database.Entities.LedgerAccount", b =>
                {
                    b.HasOne("VxPayBridge.API.Database.Entities.ClientApp", "ClientApp")
                        .WithMany()
                        .HasForeignKey("ClientAppID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientApp");
                });

            modelBuilder.Entity("VxPayBridge.API.Database.Entities.LedgerEntry", b =>
                {
                    b.HasOne("VxPayBridge.API.Database.Entities.ClientApp", "ClientApp")
                        .WithMany()
                        .HasForeignKey("ClientAppID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VxPayBridge.API.Database.Entities.LedgerAccount", "LedgerAccount")
                        .WithMany()
                        .HasForeignKey("LedgerAccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VxPayBridge.API.Database.Entities.PaymentTransaction", "PaymentTransaction")
                        .WithMany()
                        .HasForeignKey("PaymentTransactionID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VxPayBridge.API.Database.Entities.Withdrawal", "Withdrawal")
                        .WithMany()
                        .HasForeignKey("WithdrawalID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClientApp");

                    b.Navigation("LedgerAccount");

                    b.Navigation("PaymentTransaction");

                    b.Navigation("Withdrawal");
                });

            modelBuilder.Entity("VxPayBridge.API.Database.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("VxPayBridge.API.Database.Entities.ClientApp", "ClientApp")
                        .WithMany()
                        .HasForeignKey("ClientAppID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientApp");
                });

            modelBuilder.Entity("VxPayBridge.API.Database.Entities.UserOtp", b =>
                {
                    b.HasOne("VxPayBridge.API.Database.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VxPayBridge.API.Database.Entities.WebhookEvent", b =>
                {
                    b.HasOne("VxPayBridge.API.Database.Entities.ClientApp", "ClientApp")
                        .WithMany()
                        .HasForeignKey("ClientAppID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientApp");
                });

            modelBuilder.Entity("VxPayBridge.API.Database.Entities.Withdrawal", b =>
                {
                    b.HasOne("VxPayBridge.API.Database.Entities.ClientApp", "ClientApp")
                        .WithMany()
                        .HasForeignKey("ClientAppID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VxPayBridge.API.Database.Entities.LedgerAccount", "LedgerAccount")
                        .WithMany()
                        .HasForeignKey("LedgerAccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientApp");

                    b.Navigation("LedgerAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
